<?php
/**
 * @file
 * Google Analytics CLF Search Event Tracking.
 */

/**
 * Implements hook_google_analytics_et_api().
 */
function clf_ga_tracking_google_analytics_et_api() {
  return array(
    array(
      'event' => 'submit',
      'selector' => '.form-search',
      'category' => 'CLF search',
      'action' => 'enter',
      'label' => '%searchterm',
      'value' => 0,
      'noninteraction' => TRUE,
      // Requires patch from to include tokens.
      // @see https://www.drupal.org/node/1778250#comment-11965091
      'tokens' => array(
        '%searchterm' => array(
          'selector' => '.form-search .input-xlarge.search-query',
          'method' => 'val',
        ),
      ),
    ),
  );
}
